/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthenticateddashboardRouteRouteImport } from './routes/_authenticated/(dashboard)/route'
import { Route as authAuthRouteRouteImport } from './routes/(auth)/auth/route'
import { Route as AuthenticateddashboardDashboardRouteImport } from './routes/_authenticated/(dashboard)/dashboard'
import { Route as authAuthCallbackRouteImport } from './routes/(auth)/auth/callback'
import { Route as authAuthAuthViewRouteImport } from './routes/(auth)/auth/$authView'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticateddashboardRouteRoute =
  AuthenticateddashboardRouteRouteImport.update({
    id: '/_authenticated/(dashboard)',
    path: '',
    getParentRoute: () => rootRouteImport,
  } as any)
const authAuthRouteRoute = authAuthRouteRouteImport.update({
  id: '/(auth)/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateddashboardDashboardRoute =
  AuthenticateddashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticateddashboardRouteRoute,
  } as any)
const authAuthCallbackRoute = authAuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => authAuthRouteRoute,
} as any)
const authAuthAuthViewRoute = authAuthAuthViewRouteImport.update({
  id: '/$authView',
  path: '/$authView',
  getParentRoute: () => authAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/auth': typeof authAuthRouteRouteWithChildren
  '/auth/$authView': typeof authAuthAuthViewRoute
  '/auth/callback': typeof authAuthCallbackRoute
  '/dashboard': typeof AuthenticateddashboardDashboardRoute
}
export interface FileRoutesByTo {
  '/unauthorized': typeof UnauthorizedRoute
  '/auth': typeof authAuthRouteRouteWithChildren
  '/': typeof PublicIndexRoute
  '/auth/$authView': typeof authAuthAuthViewRoute
  '/auth/callback': typeof authAuthCallbackRoute
  '/dashboard': typeof AuthenticateddashboardDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/(auth)/auth': typeof authAuthRouteRouteWithChildren
  '/_authenticated/(dashboard)': typeof AuthenticateddashboardRouteRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/(auth)/auth/$authView': typeof authAuthAuthViewRoute
  '/(auth)/auth/callback': typeof authAuthCallbackRoute
  '/_authenticated/(dashboard)/dashboard': typeof AuthenticateddashboardDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/auth'
    | '/auth/$authView'
    | '/auth/callback'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unauthorized'
    | '/auth'
    | '/'
    | '/auth/$authView'
    | '/auth/callback'
    | '/dashboard'
  id:
    | '__root__'
    | '/_public'
    | '/unauthorized'
    | '/(auth)/auth'
    | '/_authenticated/(dashboard)'
    | '/_public/'
    | '/(auth)/auth/$authView'
    | '/(auth)/auth/callback'
    | '/_authenticated/(dashboard)/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  authAuthRouteRoute: typeof authAuthRouteRouteWithChildren
  AuthenticateddashboardRouteRoute: typeof AuthenticateddashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/(dashboard)': {
      id: '/_authenticated/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticateddashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth': {
      id: '/(auth)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/(dashboard)/dashboard': {
      id: '/_authenticated/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticateddashboardDashboardRouteImport
      parentRoute: typeof AuthenticateddashboardRouteRoute
    }
    '/(auth)/auth/callback': {
      id: '/(auth)/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof authAuthCallbackRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
    '/(auth)/auth/$authView': {
      id: '/(auth)/auth/$authView'
      path: '/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof authAuthAuthViewRouteImport
      parentRoute: typeof authAuthRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface authAuthRouteRouteChildren {
  authAuthAuthViewRoute: typeof authAuthAuthViewRoute
  authAuthCallbackRoute: typeof authAuthCallbackRoute
}

const authAuthRouteRouteChildren: authAuthRouteRouteChildren = {
  authAuthAuthViewRoute: authAuthAuthViewRoute,
  authAuthCallbackRoute: authAuthCallbackRoute,
}

const authAuthRouteRouteWithChildren = authAuthRouteRoute._addFileChildren(
  authAuthRouteRouteChildren,
)

interface AuthenticateddashboardRouteRouteChildren {
  AuthenticateddashboardDashboardRoute: typeof AuthenticateddashboardDashboardRoute
}

const AuthenticateddashboardRouteRouteChildren: AuthenticateddashboardRouteRouteChildren =
  {
    AuthenticateddashboardDashboardRoute: AuthenticateddashboardDashboardRoute,
  }

const AuthenticateddashboardRouteRouteWithChildren =
  AuthenticateddashboardRouteRoute._addFileChildren(
    AuthenticateddashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  authAuthRouteRoute: authAuthRouteRouteWithChildren,
  AuthenticateddashboardRouteRoute:
    AuthenticateddashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
